### ISSUE TITLE
Error in get_graph() function

### ISSUE THREAD

**Issue by annaritz** [adbharadwaj/graphspace-python#14]
Hi @adbharadwaj  - I am getting an error thrown by the get_graph() function. I get this error when I go through your tutorial [here](http://manual.graphspace.org/projects/graphspace-python/en/latest/tutorial/tutorial.html#updating-a-graph-on-graphspace).  The issue occurs when I attempt to get the graph by `graph_name` rather than `graph_id`.  (I am trying to write a function that will post a graph if it doesn't exist and update a graph if it does).

This is for a lab tomorrow, so if it's a quick fix that would be great. Thanks!

```
Traceback (most recent call last):
  File "tutorial.py", line 18, in <module>
    graph = graphspace.get_graph(graph_name='My Sample Graph')
  File "/Library/Python/2.7/site-packages/graphspace_python/api/endpoint/graphs.py", line 101, in get_graph
    response.get('graphs')[0]
  File "/Library/Python/2.7/site-packages/graphspace_python/api/obj/api_response.py", line 28, in __init__
    self._parse(response_type, Graph, response)
  File "/Library/Python/2.7/site-packages/graphspace_python/api/obj/response_object.py", line 45, in _parse
    self.__setattr__(field_name, cls_name(response))
  File "/Library/Python/2.7/site-packages/graphspace_python/api/obj/graph.py", line 51, in __init__
    self.set_data(self.graph_json['data'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by annaritz** [comment]
Hi - the error also occurs in `get_my_graphs` and `update_graph` as well.  It seems to have to do with the response object not being parsed correctly.

**Comment by sandeepm96** [comment]
@annaritz This issue has been fixed in this [PR](https://github.com/adbharadwaj/graphspace-python/pull/12), in the commit : [https://github.com/adbharadwaj/graphspace-python/pull/12/commits/8fe2fb1d4017d5b6912540b0c2b14013948f2b49](https://github.com/adbharadwaj/graphspace-python/pull/12/commits/8fe2fb1d4017d5b6912540b0c2b14013948f2b49)

**Comment by annaritz** [comment]
Thanks for the info!  Is there a way to release a new version of the module so my students can install this version using `pip install`?

**Comment by sandeepm96** [comment]
@adbharadwaj will be merging the PR soon and then we can make a new release.

**Comment by annaritz** [comment]
Great, thanks @sandeepm96 for the update. I'll close this issue then.

**Comment by adbharadwaj** [comment]
The pull request has been merged. It should work fine now.
