### ISSUE TITLE
get_graph_layout() bug

### ISSUE THREAD

**Issue by jlaw9** [adbharadwaj/graphspace-python#17]
Line of code:
```
layout = gs.get_graph_layout(graph_name=graph_name,layout_name=layout_name)
```
Error:
```
File "/home/jeffl/git-workspace/graphspace-python/graphspace_python/api/endpoint/layouts.py", line 337, in get_graph_layout
graph = self.get_graph(graph_name=graph_name)
AttributeError: 'Layouts' object has no attribute 'get_graph'
```

Looking in `api/endpoint/layouts.py` and `api/endpoint/graphs.py`, the `get_graph()` function is now solely in `graphs.py`. As a temporary fix, I copied `get_graph()` to `layouts.py`, but the correct solution would be to import and call the function from `graphs.py`.

**Comment by sandeepm96** [comment]
Closing this issue since it has been fixed here #18
