### ISSUE TITLE
graphspace_python doesn't work with NetworkX 2.1

### ISSUE THREAD

**Issue by annaritz** [adbharadwaj/graphspace-python#20]
graphspace_python currently requires networkx version 1.11; however, the most recent version of networkx is 2.1. Are there plans to make graphspace_python compatible with networkx 2.1?  Some information about migrating from 1 to 2 is here:

https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by domitry** [comment]
Maybe this patch is enough.
https://gist.github.com/domitry/7aa70a1ebab06d183fbaa45cd1cbe255

However the module with the patch does not work with NetworkX 1.x.

**Comment by jlaw9** [comment]
Thanks @domitry. Maybe we could just add a NetworkX version check, and use the corresponding add_node function?

@adbharadwaj what do you think?

Just adding this to be clear. The actual error when using networkx 2.1 is "Error: add_node() takes exactly 2 arguments (3 given)"

**Comment by annaritz** [comment]
Hi All - is this a relatively quick fix that can be done soon?  @miriambern and I are trying to visualize a graph that relies on networkx 2.1.  Thanks!

**Comment by sandeepm96** [comment]
Hi @annaritz, I am working on the fix now. I will submit a PR at the earliest and we can make a new release. @adbharadwaj

**Comment by annaritz** [comment]
Hi @sandeepm96  - I see you have fixed this issue - is there a new release?

**Comment by jlaw9** [comment]
This issue can be closed now @adbharadwaj
