### ISSUE TITLE
requests version 2.10.0

### ISSUE THREAD

**Issue by agitter** [adbharadwaj/graphspace-python#36]
The requirements file specifies `requests==2.10.0`.  I'm trying to install GraphSpace into a conda environment, and this old version of `requests` conflicts with other packages that require a newer version.

Is GraphSpace compatible with a newer version of `requests`?  If so, could the requirements file be updated to `requests>=2.10.0`?

I noticed an automated pull request to update the version https://github.com/adbharadwaj/graphspace-python/pull/32

**Comment by agitter** [comment]
@adbharadwaj do you have any thoughts on the `requests` version requirement?  We're waiting to merge https://github.com/Reed-CompBio/spras/pull/38 in another project until this is resolved.  Thanks for the help.

**Comment by adbharadwaj** [comment]
Just merged the PR. Sorry for the delay!
